begin_unit
begin_comment
comment|/*  * $Id$  *   * Copyright 1997 Hewlett-Packard Company  *   * This file may be copied, modified and distributed only in  * accordance with the terms of the limited licence contained  * in the accompanying file LICENSE.TXT.  */
end_comment
begin_package
DECL|package|hplb.xml
package|package
name|hplb
operator|.
name|xml
package|;
end_package
begin_import
import|import
name|hplb
operator|.
name|org
operator|.
name|w3c
operator|.
name|dom
operator|.
name|*
import|;
end_import
begin_comment
comment|/**  *   * @author  Anders Kristensen  */
end_comment
begin_class
DECL|class|AttrImpl
specifier|public
specifier|final
class|class
name|AttrImpl
implements|implements
name|Attribute
block|{
DECL|field|name
specifier|protected
name|String
name|name
decl_stmt|;
DECL|field|value
specifier|protected
name|Node
name|value
decl_stmt|;
DECL|field|specified
specifier|protected
name|boolean
name|specified
decl_stmt|;
DECL|method|AttrImpl
specifier|public
name|AttrImpl
parameter_list|(
name|String
name|name
parameter_list|,
name|String
name|value
parameter_list|)
block|{
name|this
argument_list|(
name|name
argument_list|,
operator|new
name|TextImpl
argument_list|(
name|Node
operator|.
name|TEXT
argument_list|,
name|value
argument_list|)
argument_list|,
literal|true
argument_list|)
expr_stmt|;
block|}
DECL|method|AttrImpl
specifier|public
name|AttrImpl
parameter_list|(
name|String
name|name
parameter_list|,
name|Node
name|value
parameter_list|,
name|boolean
name|specified
parameter_list|)
block|{
name|this
operator|.
name|name
operator|=
name|name
expr_stmt|;
name|this
operator|.
name|value
operator|=
name|value
expr_stmt|;
name|this
operator|.
name|specified
operator|=
name|specified
expr_stmt|;
block|}
DECL|method|getName
specifier|public
name|String
name|getName
parameter_list|()
block|{
return|return
name|name
return|;
block|}
DECL|method|getValue
specifier|public
name|Node
name|getValue
parameter_list|()
block|{
return|return
name|value
return|;
block|}
DECL|method|setValue
specifier|public
name|void
name|setValue
parameter_list|(
name|Node
name|arg
parameter_list|)
block|{
name|value
operator|=
name|arg
expr_stmt|;
block|}
DECL|method|getSpecified
specifier|public
name|boolean
name|getSpecified
parameter_list|()
block|{
return|return
name|specified
return|;
block|}
DECL|method|setSpecified
specifier|public
name|void
name|setSpecified
parameter_list|(
name|boolean
name|arg
parameter_list|)
block|{
name|specified
operator|=
name|arg
expr_stmt|;
block|}
DECL|method|toString
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
name|value
operator|.
name|toString
argument_list|()
return|;
block|}
block|}
end_class
end_unit
