begin_unit
begin_package
DECL|package|org.apache.solr.rest.schema
package|package
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|rest
operator|.
name|schema
package|;
end_package
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *     http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment
begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|common
operator|.
name|params
operator|.
name|CommonParams
import|;
end_import
begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|rest
operator|.
name|GETable
import|;
end_import
begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|solr
operator|.
name|schema
operator|.
name|IndexSchema
import|;
end_import
begin_import
import|import
name|org
operator|.
name|restlet
operator|.
name|representation
operator|.
name|Representation
import|;
end_import
begin_import
import|import
name|org
operator|.
name|restlet
operator|.
name|resource
operator|.
name|ResourceException
import|;
end_import
begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import
begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import
begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Arrays
import|;
end_import
begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashSet
import|;
end_import
begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import
begin_comment
comment|/**  * This class responds to requests at /solr/(corename)/schema/copyfields  *   *<p/>  *   * To restrict the set of copyFields in the response, specify one or both  * of the following as query parameters, with values as space and/or comma  * separated dynamic or explicit field names:  *   *<ul>  *<li>dest.fl: include copyFields that have one of these as a destination</li>  *<li>source.fl: include copyFields that have one of these as a source</li>  *</ul>  *   * If both dest.fl and source.fl are given as query parameters, the copyfields  * in the response will be restricted to those that match any of the destinations  * in dest.fl and also match any of the sources in source.fl.  */
end_comment
begin_class
DECL|class|CopyFieldCollectionResource
specifier|public
class|class
name|CopyFieldCollectionResource
extends|extends
name|BaseFieldResource
implements|implements
name|GETable
block|{
DECL|field|log
specifier|private
specifier|static
specifier|final
name|Logger
name|log
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|CopyFieldCollectionResource
operator|.
name|class
argument_list|)
decl_stmt|;
DECL|field|SOURCE_FIELD_LIST
specifier|private
specifier|static
specifier|final
name|String
name|SOURCE_FIELD_LIST
init|=
name|IndexSchema
operator|.
name|SOURCE
operator|+
literal|"."
operator|+
name|CommonParams
operator|.
name|FL
decl_stmt|;
DECL|field|DESTINATION_FIELD_LIST
specifier|private
specifier|static
specifier|final
name|String
name|DESTINATION_FIELD_LIST
init|=
name|IndexSchema
operator|.
name|DESTINATION
operator|+
literal|"."
operator|+
name|CommonParams
operator|.
name|FL
decl_stmt|;
DECL|field|requestedSourceFields
specifier|private
name|Set
argument_list|<
name|String
argument_list|>
name|requestedSourceFields
decl_stmt|;
DECL|field|requestedDestinationFields
specifier|private
name|Set
argument_list|<
name|String
argument_list|>
name|requestedDestinationFields
decl_stmt|;
DECL|method|CopyFieldCollectionResource
specifier|public
name|CopyFieldCollectionResource
parameter_list|()
block|{
name|super
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|doInit
specifier|public
name|void
name|doInit
parameter_list|()
throws|throws
name|ResourceException
block|{
name|super
operator|.
name|doInit
argument_list|()
expr_stmt|;
if|if
condition|(
name|isExisting
argument_list|()
condition|)
block|{
name|String
name|sourceFieldListParam
init|=
name|getSolrRequest
argument_list|()
operator|.
name|getParams
argument_list|()
operator|.
name|get
argument_list|(
name|SOURCE_FIELD_LIST
argument_list|)
decl_stmt|;
if|if
condition|(
literal|null
operator|!=
name|sourceFieldListParam
condition|)
block|{
name|String
index|[]
name|fields
init|=
name|sourceFieldListParam
operator|.
name|trim
argument_list|()
operator|.
name|split
argument_list|(
literal|"[,\\s]+"
argument_list|)
decl_stmt|;
if|if
condition|(
name|fields
operator|.
name|length
operator|>
literal|0
condition|)
block|{
name|requestedSourceFields
operator|=
operator|new
name|HashSet
argument_list|<
name|String
argument_list|>
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
name|fields
argument_list|)
argument_list|)
expr_stmt|;
name|requestedSourceFields
operator|.
name|remove
argument_list|(
literal|""
argument_list|)
expr_stmt|;
comment|// Remove empty values, if any
block|}
block|}
name|String
name|destinationFieldListParam
init|=
name|getSolrRequest
argument_list|()
operator|.
name|getParams
argument_list|()
operator|.
name|get
argument_list|(
name|DESTINATION_FIELD_LIST
argument_list|)
decl_stmt|;
if|if
condition|(
literal|null
operator|!=
name|destinationFieldListParam
condition|)
block|{
name|String
index|[]
name|fields
init|=
name|destinationFieldListParam
operator|.
name|trim
argument_list|()
operator|.
name|split
argument_list|(
literal|"[,\\s]+"
argument_list|)
decl_stmt|;
if|if
condition|(
name|fields
operator|.
name|length
operator|>
literal|0
condition|)
block|{
name|requestedDestinationFields
operator|=
operator|new
name|HashSet
argument_list|<
name|String
argument_list|>
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
name|fields
argument_list|)
argument_list|)
expr_stmt|;
name|requestedDestinationFields
operator|.
name|remove
argument_list|(
literal|""
argument_list|)
expr_stmt|;
comment|// Remove empty values, if any
block|}
block|}
block|}
block|}
annotation|@
name|Override
DECL|method|get
specifier|public
name|Representation
name|get
parameter_list|()
block|{
try|try
block|{
name|getSolrResponse
argument_list|()
operator|.
name|add
argument_list|(
name|IndexSchema
operator|.
name|COPY_FIELDS
argument_list|,
name|getSchema
argument_list|()
operator|.
name|getCopyFieldProperties
argument_list|(
literal|true
argument_list|,
name|requestedSourceFields
argument_list|,
name|requestedDestinationFields
argument_list|)
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
name|getSolrResponse
argument_list|()
operator|.
name|setException
argument_list|(
name|e
argument_list|)
expr_stmt|;
block|}
name|handlePostExecution
argument_list|(
name|log
argument_list|)
expr_stmt|;
return|return
operator|new
name|SolrOutputRepresentation
argument_list|()
return|;
block|}
block|}
end_class
end_unit
