begin_unit
begin_comment
comment|/* Generated By:JavaCC: Do not edit this line. HTMLParserConstants.java */
end_comment
begin_package
DECL|package|org.apache.lucene.demo.html
package|package
name|org
operator|.
name|apache
operator|.
name|lucene
operator|.
name|demo
operator|.
name|html
package|;
end_package
begin_comment
comment|/**  * Token literal values and constants.  * Generated by org.javacc.parser.OtherFilesGen#start()  */
end_comment
begin_interface
DECL|interface|HTMLParserConstants
specifier|public
interface|interface
name|HTMLParserConstants
block|{
comment|/** End of File. */
DECL|field|EOF
name|int
name|EOF
init|=
literal|0
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|ScriptStart
name|int
name|ScriptStart
init|=
literal|1
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|TagName
name|int
name|TagName
init|=
literal|2
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|DeclName
name|int
name|DeclName
init|=
literal|3
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|Comment1
name|int
name|Comment1
init|=
literal|4
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|Comment2
name|int
name|Comment2
init|=
literal|5
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|Word
name|int
name|Word
init|=
literal|6
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|LET
name|int
name|LET
init|=
literal|7
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|NUM
name|int
name|NUM
init|=
literal|8
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|HEX
name|int
name|HEX
init|=
literal|9
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|Entity
name|int
name|Entity
init|=
literal|10
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|Space
name|int
name|Space
init|=
literal|11
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|SP
name|int
name|SP
init|=
literal|12
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|Punct
name|int
name|Punct
init|=
literal|13
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|ScriptText
name|int
name|ScriptText
init|=
literal|14
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|ScriptEnd
name|int
name|ScriptEnd
init|=
literal|15
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|ArgName
name|int
name|ArgName
init|=
literal|16
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|ArgEquals
name|int
name|ArgEquals
init|=
literal|17
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|TagEnd
name|int
name|TagEnd
init|=
literal|18
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|ArgValue
name|int
name|ArgValue
init|=
literal|19
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|ArgQuote1
name|int
name|ArgQuote1
init|=
literal|20
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|ArgQuote2
name|int
name|ArgQuote2
init|=
literal|21
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|Quote1Text
name|int
name|Quote1Text
init|=
literal|23
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|CloseQuote1
name|int
name|CloseQuote1
init|=
literal|24
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|Quote2Text
name|int
name|Quote2Text
init|=
literal|25
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|CloseQuote2
name|int
name|CloseQuote2
init|=
literal|26
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|CommentText1
name|int
name|CommentText1
init|=
literal|27
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|CommentEnd1
name|int
name|CommentEnd1
init|=
literal|28
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|CommentText2
name|int
name|CommentText2
init|=
literal|29
decl_stmt|;
comment|/** RegularExpression Id. */
DECL|field|CommentEnd2
name|int
name|CommentEnd2
init|=
literal|30
decl_stmt|;
comment|/** Lexical state. */
DECL|field|DEFAULT
name|int
name|DEFAULT
init|=
literal|0
decl_stmt|;
comment|/** Lexical state. */
DECL|field|WithinScript
name|int
name|WithinScript
init|=
literal|1
decl_stmt|;
comment|/** Lexical state. */
DECL|field|WithinTag
name|int
name|WithinTag
init|=
literal|2
decl_stmt|;
comment|/** Lexical state. */
DECL|field|AfterEquals
name|int
name|AfterEquals
init|=
literal|3
decl_stmt|;
comment|/** Lexical state. */
DECL|field|WithinQuote1
name|int
name|WithinQuote1
init|=
literal|4
decl_stmt|;
comment|/** Lexical state. */
DECL|field|WithinQuote2
name|int
name|WithinQuote2
init|=
literal|5
decl_stmt|;
comment|/** Lexical state. */
DECL|field|WithinComment1
name|int
name|WithinComment1
init|=
literal|6
decl_stmt|;
comment|/** Lexical state. */
DECL|field|WithinComment2
name|int
name|WithinComment2
init|=
literal|7
decl_stmt|;
comment|/** Literal token values. */
DECL|field|tokenImage
name|String
index|[]
name|tokenImage
init|=
block|{
literal|"<EOF>"
block|,
literal|"\"<script\""
block|,
literal|"<TagName>"
block|,
literal|"<DeclName>"
block|,
literal|"\"<!--\""
block|,
literal|"\"<!\""
block|,
literal|"<Word>"
block|,
literal|"<LET>"
block|,
literal|"<NUM>"
block|,
literal|"<HEX>"
block|,
literal|"<Entity>"
block|,
literal|"<Space>"
block|,
literal|"<SP>"
block|,
literal|"<Punct>"
block|,
literal|"<ScriptText>"
block|,
literal|"<ScriptEnd>"
block|,
literal|"<ArgName>"
block|,
literal|"\"=\""
block|,
literal|"<TagEnd>"
block|,
literal|"<ArgValue>"
block|,
literal|"\"\\\'\""
block|,
literal|"\"\\\"\""
block|,
literal|"<token of kind 22>"
block|,
literal|"<Quote1Text>"
block|,
literal|"<CloseQuote1>"
block|,
literal|"<Quote2Text>"
block|,
literal|"<CloseQuote2>"
block|,
literal|"<CommentText1>"
block|,
literal|"\"-->\""
block|,
literal|"<CommentText2>"
block|,
literal|"\">\""
block|,   }
decl_stmt|;
block|}
end_interface
end_unit
